dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t gitbook .
      - docker images
      - docker tag gitbook $DOCKER_USERNAME/gitbook
      - docker push $DOCKER_USERNAME/gitbook
